/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize};
use std::sync::Arc;

#[cfg_attr(feature = "mockall", automock)]
#[async_trait]
pub trait DeploymentsApi: Send + Sync {
    async fn create_deployment<'workspace_id, 'application_id>(
        &self,
        workspace_id: &str,
        application_id: &str,
    ) -> Result<models::CreateDeploymentSuccess, Error<CreateDeploymentError>>;
    async fn list_deployments<'workspace_id, 'application_id>(
        &self,
        workspace_id: &str,
        application_id: &str,
    ) -> Result<models::ListDeploymentsSuccess, Error<ListDeploymentsError>>;
    async fn read_deployment<'workspace_id, 'application_id, 'deployment_id>(
        &self,
        workspace_id: &str,
        application_id: &str,
        deployment_id: u64,
    ) -> Result<models::ReadDeploymentSuccess, Error<ReadDeploymentError>>;
}

pub struct DeploymentsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl DeploymentsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl DeploymentsApi for DeploymentsApiClient {
    async fn create_deployment<'workspace_id, 'application_id>(
        &self,
        workspace_id: &str,
        application_id: &str,
    ) -> Result<models::CreateDeploymentSuccess, Error<CreateDeploymentError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/v1/workspaces/{workspace_id}/applications/{application_id}/deployments",
            local_var_configuration.base_path,
            workspace_id = crate::apis::urlencode(workspace_id),
            application_id = crate::apis::urlencode(application_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            serde_json::from_str(&local_var_content).map_err(Error::from)
        } else {
            let local_var_entity: Option<CreateDeploymentError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn list_deployments<'workspace_id, 'application_id>(
        &self,
        workspace_id: &str,
        application_id: &str,
    ) -> Result<models::ListDeploymentsSuccess, Error<ListDeploymentsError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/v1/workspaces/{workspace_id}/applications/{application_id}/deployments",
            local_var_configuration.base_path,
            workspace_id = crate::apis::urlencode(workspace_id),
            application_id = crate::apis::urlencode(application_id)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            serde_json::from_str(&local_var_content).map_err(Error::from)
        } else {
            let local_var_entity: Option<ListDeploymentsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn read_deployment<'workspace_id, 'application_id, 'deployment_id>(
        &self,
        workspace_id: &str,
        application_id: &str,
        deployment_id: u64,
    ) -> Result<models::ReadDeploymentSuccess, Error<ReadDeploymentError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/workspaces/{workspace_id}/applications/{application_id}/deployments/{deployment_id}", local_var_configuration.base_path, workspace_id=crate::apis::urlencode(workspace_id), application_id=crate::apis::urlencode(application_id), deployment_id=deployment_id);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            serde_json::from_str(&local_var_content).map_err(Error::from)
        } else {
            let local_var_entity: Option<ReadDeploymentError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`create_deployment`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateDeploymentError {
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_deployments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListDeploymentsError {
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`read_deployment`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReadDeploymentError {
    Status500(),
    UnknownValue(serde_json::Value),
}
