/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize};
use std::sync::Arc;

#[cfg_attr(feature = "mockall", automock)]
#[async_trait]
pub trait DeploymentStatesApi: Send + Sync {
    async fn list_deployment_states<'workspace_id, 'application_id, 'deployment_id, 'status>(
        &self,
        workspace_id: u32,
        application_id: u32,
        deployment_id: u64,
        status: Option<models::DeploymentStateStatus>,
    ) -> Result<models::ListDeploymentStatesSuccess, Error<ListDeploymentStatesError>>;
    async fn refresh_deployment_state<'workspace_id, 'application_id, 'deployment_id, 'state_id>(
        &self,
        workspace_id: u32,
        application_id: u32,
        deployment_id: u64,
        state_id: u64,
    ) -> Result<models::UpdateDeploymentStateSuccess, Error<RefreshDeploymentStateError>>;
    async fn update_deployment_state<
        'workspace_id,
        'application_id,
        'deployment_id,
        'state_id,
        'update_deployment_state_request,
    >(
        &self,
        workspace_id: u32,
        application_id: u32,
        deployment_id: u64,
        state_id: u64,
        update_deployment_state_request: models::UpdateDeploymentStateRequest,
    ) -> Result<models::UpdateDeploymentStateSuccess, Error<UpdateDeploymentStateError>>;
}

pub struct DeploymentStatesApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl DeploymentStatesApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl DeploymentStatesApi for DeploymentStatesApiClient {
    async fn list_deployment_states<'workspace_id, 'application_id, 'deployment_id, 'status>(
        &self,
        workspace_id: u32,
        application_id: u32,
        deployment_id: u64,
        status: Option<models::DeploymentStateStatus>,
    ) -> Result<models::ListDeploymentStatesSuccess, Error<ListDeploymentStatesError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/workspaces/{workspace_id}/applications/{application_id}/deployments/{deployment_id}/states", local_var_configuration.base_path, workspace_id=workspace_id, application_id=application_id, deployment_id=deployment_id);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_str) = status {
            local_var_req_builder =
                local_var_req_builder.query(&[("status", &local_var_str.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            serde_json::from_str(&local_var_content).map_err(Error::from)
        } else {
            let local_var_entity: Option<ListDeploymentStatesError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn refresh_deployment_state<'workspace_id, 'application_id, 'deployment_id, 'state_id>(
        &self,
        workspace_id: u32,
        application_id: u32,
        deployment_id: u64,
        state_id: u64,
    ) -> Result<models::UpdateDeploymentStateSuccess, Error<RefreshDeploymentStateError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/workspaces/{workspace_id}/applications/{application_id}/deployments/{deployment_id}/states/{state_id}/refresh", local_var_configuration.base_path, workspace_id=workspace_id, application_id=application_id, deployment_id=deployment_id, state_id=state_id);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            serde_json::from_str(&local_var_content).map_err(Error::from)
        } else {
            let local_var_entity: Option<RefreshDeploymentStateError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn update_deployment_state<
        'workspace_id,
        'application_id,
        'deployment_id,
        'state_id,
        'update_deployment_state_request,
    >(
        &self,
        workspace_id: u32,
        application_id: u32,
        deployment_id: u64,
        state_id: u64,
        update_deployment_state_request: models::UpdateDeploymentStateRequest,
    ) -> Result<models::UpdateDeploymentStateSuccess, Error<UpdateDeploymentStateError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/workspaces/{workspace_id}/applications/{application_id}/deployments/{deployment_id}/states/{state_id}", local_var_configuration.base_path, workspace_id=workspace_id, application_id=application_id, deployment_id=deployment_id, state_id=state_id);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PATCH, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&update_deployment_state_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            serde_json::from_str(&local_var_content).map_err(Error::from)
        } else {
            let local_var_entity: Option<UpdateDeploymentStateError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`list_deployment_states`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListDeploymentStatesError {
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`refresh_deployment_state`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RefreshDeploymentStateError {
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_deployment_state`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateDeploymentStateError {
    Status500(),
    UnknownValue(serde_json::Value),
}
