/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use serde::{Deserialize, Serialize};
use std::sync::Arc;

#[cfg_attr(feature = "mockall", automock)]
#[async_trait]
pub trait ResponseCodeMetricsApi: Send + Sync {
    async fn create_response_code_metrics<
        'workspace_id,
        'application_id,
        'deployment_id,
        'create_response_code_metrics_request,
    >(
        &self,
        workspace_id: &str,
        application_id: &str,
        deployment_id: u64,
        create_response_code_metrics_request: models::CreateResponseCodeMetricsRequest,
    ) -> Result<models::CreateResponseCodeMetricsSuccess, Error<CreateResponseCodeMetricsError>>;
}

pub struct ResponseCodeMetricsApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl ResponseCodeMetricsApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

#[async_trait]
impl ResponseCodeMetricsApi for ResponseCodeMetricsApiClient {
    async fn create_response_code_metrics<
        'workspace_id,
        'application_id,
        'deployment_id,
        'create_response_code_metrics_request,
    >(
        &self,
        workspace_id: &str,
        application_id: &str,
        deployment_id: u64,
        create_response_code_metrics_request: models::CreateResponseCodeMetricsRequest,
    ) -> Result<models::CreateResponseCodeMetricsSuccess, Error<CreateResponseCodeMetricsError>>
    {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/workspaces/{workspace_id}/applications/{application_id}/deployments/{deployment_id}/metrics/response-codes", local_var_configuration.base_path, workspace_id=crate::apis::urlencode(workspace_id), application_id=crate::apis::urlencode(application_id), deployment_id=deployment_id);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_token) = local_var_configuration.bearer_access_token {
            local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
        };
        local_var_req_builder = local_var_req_builder.json(&create_response_code_metrics_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            serde_json::from_str(&local_var_content).map_err(Error::from)
        } else {
            let local_var_entity: Option<CreateResponseCodeMetricsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`create_response_code_metrics`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateResponseCodeMetricsError {
    Status500(),
    UnknownValue(serde_json::Value),
}
