/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApplicationType : An identifier of what kind of application we're tracking.
/// An identifier of what kind of application we're tracking.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApplicationType {
    #[serde(rename = "web_service")]
    WebService,
}

impl std::fmt::Display for ApplicationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::WebService => write!(f, "web_service"),
        }
    }
}

impl Default for ApplicationType {
    fn default() -> ApplicationType {
        Self::WebService
    }
}
