/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApplicationGroup {
    #[serde(rename = "canary")]
    Canary,
    #[serde(rename = "baseline")]
    Baseline,

}

impl std::fmt::Display for ApplicationGroup {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Canary => write!(f, "canary"),
            Self::Baseline => write!(f, "baseline"),
        }
    }
}

impl Default for ApplicationGroup {
    fn default() -> ApplicationGroup {
        Self::Canary
    }
}

