/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationSummary {
    #[serde(rename = "app_type")]
    pub app_type: models::ApplicationType,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "id")]
    pub id: u32,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ApplicationSummary {
    pub fn new(
        app_type: models::ApplicationType,
        created_at: String,
        display_name: String,
        id: u32,
        updated_at: String,
    ) -> ApplicationSummary {
        ApplicationSummary {
            app_type,
            created_at,
            display_name,
            id,
            updated_at,
        }
    }
}
