/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApplicationGroup {
    #[serde(rename = "canary")]
    Canary,
    #[serde(rename = "baseline")]
    Baseline,

}

impl ToString for ApplicationGroup {
    fn to_string(&self) -> String {
        match self {
            Self::Canary => String::from("canary"),
            Self::Baseline => String::from("baseline"),
        }
    }
}

impl Default for ApplicationGroup {
    fn default() -> ApplicationGroup {
        Self::Canary
    }
}

