/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Cloud {
    #[serde(rename = "Aws")]
    Aws,
    #[serde(rename = "Cloudflare")]
    Cloudflare,

}

impl std::fmt::Display for Cloud {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Aws => write!(f, "Aws"),
            Self::Cloudflare => write!(f, "Cloudflare"),
        }
    }
}

impl Default for Cloud {
    fn default() -> Cloud {
        Self::Aws
    }
}

