/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateErrorRequest {
    #[serde(rename = "logs", deserialize_with = "Option::deserialize")]
    pub logs: Option<serde_json::Value>,
    #[serde(rename = "status_code")]
    pub status_code: i32,
    #[serde(rename = "url_path")]
    pub url_path: String,
}

impl CreateErrorRequest {
    pub fn new(logs: Option<serde_json::Value>, status_code: i32, url_path: String) -> CreateErrorRequest {
        CreateErrorRequest {
            logs,
            status_code,
            url_path,
        }
    }
}

