/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateUserRequest : Expected body of user endpoint requests
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "password")]
    pub password: String,
    /// Whether the user has accepted the terms of service
    #[serde(rename = "tos_accepted")]
    pub tos_accepted: bool,
}

impl CreateUserRequest {
    /// Expected body of user endpoint requests
    pub fn new(email: String, password: String, tos_accepted: bool) -> CreateUserRequest {
        CreateUserRequest {
            email,
            password,
            tos_accepted,
        }
    }
}
