/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateResponseCodeMetricsRequest {
    #[serde(rename = "status_codes")]
    pub status_codes: Vec<models::StatusCodeMetrics>,
}

impl CreateResponseCodeMetricsRequest {
    pub fn new(status_codes: Vec<models::StatusCodeMetrics>) -> CreateResponseCodeMetricsRequest {
        CreateResponseCodeMetricsRequest {
            status_codes,
        }
    }
}

