/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDeploymentSuccess {
    #[serde(rename = "deployment")]
    pub deployment: Box<models::Deployment>,
}

impl CreateDeploymentSuccess {
    pub fn new(deployment: models::Deployment) -> CreateDeploymentSuccess {
        CreateDeploymentSuccess {
            deployment: Box::new(deployment),
        }
    }
}
