/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserSuccess {
    #[serde(rename = "user")]
    pub user: Box<models::UserDetails>,
}

impl CreateUserSuccess {
    pub fn new(user: models::UserDetails) -> CreateUserSuccess {
        CreateUserSuccess {
            user: Box::new(user),
        }
    }
}
