/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateResponseCodeMetricsRequest {
    #[serde(rename = "app_class")]
    pub app_class: models::ApplicationGroup,
    #[serde(rename = "status_2xx_count")]
    pub status_2xx_count: i32,
    #[serde(rename = "status_4xx_count")]
    pub status_4xx_count: i32,
    #[serde(rename = "status_5xx_count")]
    pub status_5xx_count: i32,
}

impl CreateResponseCodeMetricsRequest {
    pub fn new(
        app_class: models::ApplicationGroup,
        status_2xx_count: i32,
        status_4xx_count: i32,
        status_5xx_count: i32,
    ) -> CreateResponseCodeMetricsRequest {
        CreateResponseCodeMetricsRequest {
            app_class,
            status_2xx_count,
            status_4xx_count,
            status_5xx_count,
        }
    }
}
