/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateResponseCodeMetricsSuccess {
    #[serde(rename = "response_code_metrics")]
    pub response_code_metrics: Box<models::ResponseCodeMetrics>,
}

impl CreateResponseCodeMetricsSuccess {
    pub fn new(response_code_metrics: models::ResponseCodeMetrics) -> CreateResponseCodeMetricsSuccess {
        CreateResponseCodeMetricsSuccess {
            response_code_metrics: Box::new(response_code_metrics),
        }
    }
}

