/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRolloutRequest {
    #[serde(rename = "config")]
    pub config: Box<models::ApplicationConfig>,
}

impl CreateRolloutRequest {
    pub fn new(config: models::ApplicationConfig) -> CreateRolloutRequest {
        CreateRolloutRequest {
            config: Box::new(config),
        }
    }
}

