/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRolloutSuccess {
    #[serde(rename = "rollout")]
    pub rollout: Box<models::Rollout>,
}

impl CreateRolloutSuccess {
    pub fn new(rollout: models::Rollout) -> CreateRolloutSuccess {
        CreateRolloutSuccess {
            rollout: Box::new(rollout),
        }
    }
}

