/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentEventType {
    #[serde(rename = "deployment_queued")]
    DeploymentQueued,
    #[serde(rename = "deployment_ready")]
    DeploymentReady,
    #[serde(rename = "canary_deployed")]
    CanaryDeployed,
    #[serde(rename = "traffic_increased")]
    TrafficIncreased,
    #[serde(rename = "traffic_decreased")]
    TrafficDecreased,
    #[serde(rename = "promoted")]
    Promoted,
    #[serde(rename = "rolled_back")]
    RolledBack,
    #[serde(rename = "superseded")]
    Superseded,
}

impl ToString for DeploymentEventType {
    fn to_string(&self) -> String {
        match self {
            Self::DeploymentQueued => String::from("deployment_queued"),
            Self::DeploymentReady => String::from("deployment_ready"),
            Self::CanaryDeployed => String::from("canary_deployed"),
            Self::TrafficIncreased => String::from("traffic_increased"),
            Self::TrafficDecreased => String::from("traffic_decreased"),
            Self::Promoted => String::from("promoted"),
            Self::RolledBack => String::from("rolled_back"),
            Self::Superseded => String::from("superseded"),
        }
    }
}

impl Default for DeploymentEventType {
    fn default() -> DeploymentEventType {
        Self::DeploymentQueued
    }
}
