/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentState {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "deployment_id")]
    pub deployment_id: u64,
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "state_type")]
    pub state_type: models::DeploymentStateType,
    #[serde(rename = "status")]
    pub status: models::DeploymentStateStatus,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl DeploymentState {
    pub fn new(
        created_at: String,
        deployment_id: u64,
        id: u64,
        state_type: models::DeploymentStateType,
        status: models::DeploymentStateStatus,
        updated_at: String,
    ) -> DeploymentState {
        DeploymentState {
            created_at,
            deployment_id,
            id,
            state_type,
            status,
            updated_at,
        }
    }
}
