/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "promoted")]
    Promoted,
    #[serde(rename = "rolled_back")]
    RolledBack,
    #[serde(rename = "superseded")]
    Superseded,

}

impl std::fmt::Display for DeploymentStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Queued => write!(f, "queued"),
            Self::InProgress => write!(f, "in_progress"),
            Self::Promoted => write!(f, "promoted"),
            Self::RolledBack => write!(f, "rolled_back"),
            Self::Superseded => write!(f, "superseded"),
        }
    }
}

impl Default for DeploymentStatus {
    fn default() -> DeploymentStatus {
        Self::Queued
    }
}

