/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentEvent {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "event_type")]
    pub event_type: models::DeploymentEventType,
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl DeploymentEvent {
    pub fn new(created_at: String, event_type: models::DeploymentEventType, id: u64, updated_at: String) -> DeploymentEvent {
        DeploymentEvent {
            created_at,
            event_type,
            id,
            updated_at,
        }
    }
}

