/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeploymentStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "promoted")]
    Promoted,
    #[serde(rename = "rolled_back")]
    RolledBack,
    #[serde(rename = "superseded")]
    Superseded,

}

impl ToString for DeploymentStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Queued => String::from("queued"),
            Self::InProgress => String::from("in_progress"),
            Self::Promoted => String::from("promoted"),
            Self::RolledBack => String::from("rolled_back"),
            Self::Superseded => String::from("superseded"),
        }
    }
}

impl Default for DeploymentStatus {
    fn default() -> DeploymentStatus {
        Self::Queued
    }
}

