/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentEventTypeOneOf {
    #[serde(rename = "traffic_increased")]
    pub traffic_increased: Box<models::TrafficIncreasedData>,
}

impl DeploymentEventTypeOneOf {
    pub fn new(traffic_increased: models::TrafficIncreasedData) -> DeploymentEventTypeOneOf {
        DeploymentEventTypeOneOf {
            traffic_increased: Box::new(traffic_increased),
        }
    }
}

