/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Deployment {
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "app_id")]
    pub app_id: uuid::Uuid,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "events")]
    pub events: Vec<models::DeploymentEvent>,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "status")]
    pub status: models::DeploymentStatus,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Deployment {
    pub fn new(active: bool, app_id: uuid::Uuid, created_at: String, events: Vec<models::DeploymentEvent>, id: i64, status: models::DeploymentStatus, updated_at: String) -> Deployment {
        Deployment {
            active,
            app_id,
            created_at,
            events,
            id,
            status,
            updated_at,
        }
    }
}

