/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentStateDataOneOf {
    #[serde(rename = "SetCanaryTraffic")]
    pub set_canary_traffic: Box<models::DeploymentStateDataOneOfSetCanaryTraffic>,
}

impl DeploymentStateDataOneOf {
    pub fn new(
        set_canary_traffic: models::DeploymentStateDataOneOfSetCanaryTraffic,
    ) -> DeploymentStateDataOneOf {
        DeploymentStateDataOneOf {
            set_canary_traffic: Box::new(set_canary_traffic),
        }
    }
}
