/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngressConfigOneOf1 {
    #[serde(rename = "cloudflare_worker")]
    pub cloudflare_worker: Box<models::IngressConfigOneOf1CloudflareWorker>,
}

impl IngressConfigOneOf1 {
    pub fn new(cloudflare_worker: models::IngressConfigOneOf1CloudflareWorker) -> IngressConfigOneOf1 {
        IngressConfigOneOf1 {
            cloudflare_worker: Box::new(cloudflare_worker),
        }
    }
}

