/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngressConfigOneOf {
    #[serde(rename = "aws_rest_api_gateway")]
    pub aws_rest_api_gateway: Box<models::IngressConfigOneOfAwsRestApiGateway>,
}

impl IngressConfigOneOf {
    pub fn new(aws_rest_api_gateway: models::IngressConfigOneOfAwsRestApiGateway) -> IngressConfigOneOf {
        IngressConfigOneOf {
            aws_rest_api_gateway: Box::new(aws_rest_api_gateway),
        }
    }
}

