/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngressConfigOneOf1CloudflareWorker {
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "worker_name")]
    pub worker_name: String,
}

impl IngressConfigOneOf1CloudflareWorker {
    pub fn new(account_id: String, worker_name: String) -> IngressConfigOneOf1CloudflareWorker {
        IngressConfigOneOf1CloudflareWorker {
            account_id,
            worker_name,
        }
    }
}

