/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IngressConfig {
    IngressConfigOneOf(Box<models::IngressConfigOneOf>),
    IngressConfigOneOf1(Box<models::IngressConfigOneOf1>),
}

impl Default for IngressConfig {
    fn default() -> Self {
        Self::IngressConfigOneOf(Default::default())
    }
}

