/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngressConfigOneOfAwsRestApiGateway {
    #[serde(rename = "gateway_name")]
    pub gateway_name: String,
    #[serde(rename = "region")]
    pub region: String,
    #[serde(rename = "resource_method")]
    pub resource_method: String,
    #[serde(rename = "resource_path")]
    pub resource_path: String,
    #[serde(rename = "stage_name")]
    pub stage_name: String,
}

impl IngressConfigOneOfAwsRestApiGateway {
    pub fn new(gateway_name: String, region: String, resource_method: String, resource_path: String, stage_name: String) -> IngressConfigOneOfAwsRestApiGateway {
        IngressConfigOneOfAwsRestApiGateway {
            gateway_name,
            region,
            resource_method,
            resource_path,
            stage_name,
        }
    }
}

