/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListRolloutsSuccess {
    #[serde(rename = "rollouts")]
    pub rollouts: Vec<models::Rollout>,
}

impl ListRolloutsSuccess {
    pub fn new(rollouts: Vec<models::Rollout>) -> ListRolloutsSuccess {
        ListRolloutsSuccess {
            rollouts,
        }
    }
}

