/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListRolloutStatesSuccess {
    #[serde(rename = "states")]
    pub states: Vec<models::RolloutState>,
}

impl ListRolloutStatesSuccess {
    pub fn new(states: Vec<models::RolloutState>) -> ListRolloutStatesSuccess {
        ListRolloutStatesSuccess { states }
    }
}
