/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDeploymentsSuccess {
    #[serde(rename = "deployments")]
    pub deployments: Vec<models::Deployment>,
}

impl ListDeploymentsSuccess {
    pub fn new(deployments: Vec<models::Deployment>) -> ListDeploymentsSuccess {
        ListDeploymentsSuccess {
            deployments,
        }
    }
}

