/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginSuccess {
    #[serde(rename = "user")]
    pub user: Box<models::UserSummary>,
}

impl LoginSuccess {
    pub fn new(user: models::UserSummary) -> LoginSuccess {
        LoginSuccess {
            user: Box::new(user),
        }
    }
}

