/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MonitorConfig {
    MonitorConfigOneOf(Box<models::MonitorConfigOneOf>),
}

impl Default for MonitorConfig {
    fn default() -> Self {
        Self::MonitorConfigOneOf(Default::default())
    }
}
