/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorConfigOneOfAwsCloudwatchMetrics {
    #[serde(rename = "region")]
    pub region: String,
}

impl MonitorConfigOneOfAwsCloudwatchMetrics {
    pub fn new(region: String) -> MonitorConfigOneOfAwsCloudwatchMetrics {
        MonitorConfigOneOfAwsCloudwatchMetrics {
            region,
        }
    }
}

