/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorConfigOneOf1 {
    #[serde(rename = "cloudflare_workers_observability")]
    pub cloudflare_workers_observability: Box<models::IngressConfigOneOf1CloudflareWorker>,
}

impl MonitorConfigOneOf1 {
    pub fn new(cloudflare_workers_observability: models::IngressConfigOneOf1CloudflareWorker) -> MonitorConfigOneOf1 {
        MonitorConfigOneOf1 {
            cloudflare_workers_observability: Box::new(cloudflare_workers_observability),
        }
    }
}

