/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorConfigOneOf {
    #[serde(rename = "aws_cloudwatch_metrics")]
    pub aws_cloudwatch_metrics: Box<models::MonitorConfigOneOfAwsCloudwatchMetrics>,
}

impl MonitorConfigOneOf {
    pub fn new(aws_cloudwatch_metrics: models::MonitorConfigOneOfAwsCloudwatchMetrics) -> MonitorConfigOneOf {
        MonitorConfigOneOf {
            aws_cloudwatch_metrics: Box::new(aws_cloudwatch_metrics),
        }
    }
}

