/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformConfigOneOfAwsLambda {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "region")]
    pub region: String,
}

impl PlatformConfigOneOfAwsLambda {
    pub fn new(name: String, region: String) -> PlatformConfigOneOfAwsLambda {
        PlatformConfigOneOfAwsLambda { name, region }
    }
}
