/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PlatformConfig {
    PlatformConfigOneOf(Box<models::PlatformConfigOneOf>),
}

impl Default for PlatformConfig {
    fn default() -> Self {
        Self::PlatformConfigOneOf(Default::default())
    }
}
