/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformConfigOneOf {
    #[serde(rename = "aws_lambda")]
    pub aws_lambda: Box<models::PlatformConfigOneOfAwsLambda>,
}

impl PlatformConfigOneOf {
    pub fn new(aws_lambda: models::PlatformConfigOneOfAwsLambda) -> PlatformConfigOneOf {
        PlatformConfigOneOf {
            aws_lambda: Box::new(aws_lambda),
        }
    }
}

