/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadDeploymentSuccess {
    #[serde(rename = "deployment")]
    pub deployment: Box<models::Deployment>,
}

impl ReadDeploymentSuccess {
    pub fn new(deployment: models::Deployment) -> ReadDeploymentSuccess {
        ReadDeploymentSuccess {
            deployment: Box::new(deployment),
        }
    }
}

