/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadApplicationSuccess {
    #[serde(rename = "application")]
    pub application: Box<models::ApplicationDetails>,
}

impl ReadApplicationSuccess {
    pub fn new(application: models::ApplicationDetails) -> ReadApplicationSuccess {
        ReadApplicationSuccess {
            application: Box::new(application),
        }
    }
}
