/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadRolloutSuccess {
    #[serde(rename = "rollout")]
    pub rollout: Box<models::Rollout>,
}

impl ReadRolloutSuccess {
    pub fn new(rollout: models::Rollout) -> ReadRolloutSuccess {
        ReadRolloutSuccess {
            rollout: Box::new(rollout),
        }
    }
}
