/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseCodeMetrics {
    #[serde(rename = "app_group")]
    pub app_group: models::ApplicationGroup,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "deployment_id")]
    pub deployment_id: u64,
    #[serde(rename = "status_2xx_count")]
    pub status_2xx_count: u32,
    #[serde(rename = "status_4xx_count")]
    pub status_4xx_count: u32,
    #[serde(rename = "status_5xx_count")]
    pub status_5xx_count: u32,
}

impl ResponseCodeMetrics {
    pub fn new(
        app_group: models::ApplicationGroup,
        created_at: String,
        deployment_id: u64,
        status_2xx_count: u32,
        status_4xx_count: u32,
        status_5xx_count: u32,
    ) -> ResponseCodeMetrics {
        ResponseCodeMetrics {
            app_group,
            created_at,
            deployment_id,
            status_2xx_count,
            status_4xx_count,
            status_5xx_count,
        }
    }
}
