/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseCodeMetrics {
    #[serde(rename = "app_class")]
    pub app_class: models::ApplicationGroup,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "deployment_id")]
    pub deployment_id: i64,
    #[serde(rename = "status_2xx_count")]
    pub status_2xx_count: i32,
    #[serde(rename = "status_4xx_count")]
    pub status_4xx_count: i32,
    #[serde(rename = "status_5xx_count")]
    pub status_5xx_count: i32,
}

impl ResponseCodeMetrics {
    pub fn new(app_class: models::ApplicationGroup, created_at: String, deployment_id: i64, status_2xx_count: i32, status_4xx_count: i32, status_5xx_count: i32) -> ResponseCodeMetrics {
        ResponseCodeMetrics {
            app_class,
            created_at,
            deployment_id,
            status_2xx_count,
            status_4xx_count,
            status_5xx_count,
        }
    }
}

