/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RolloutStateDataOneOfSetCanaryTraffic {
    #[serde(rename = "percent_traffic")]
    pub percent_traffic: u32,
}

impl RolloutStateDataOneOfSetCanaryTraffic {
    pub fn new(percent_traffic: u32) -> RolloutStateDataOneOfSetCanaryTraffic {
        RolloutStateDataOneOfSetCanaryTraffic { percent_traffic }
    }
}
