/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RolloutEvent {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<serde_json::Value>>,
    #[serde(rename = "event_type")]
    pub event_type: models::RolloutEventType,
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl RolloutEvent {
    pub fn new(created_at: String, event_type: models::RolloutEventType, id: u64, updated_at: String) -> RolloutEvent {
        RolloutEvent {
            created_at,
            data: None,
            event_type,
            id,
            updated_at,
        }
    }
}

