/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RolloutEventType {
    #[serde(rename = "rollout_queued")]
    RolloutQueued,
    #[serde(rename = "rollout_ready")]
    RolloutReady,
    #[serde(rename = "canary_deployed")]
    CanaryDeployed,
    #[serde(rename = "traffic_increased")]
    TrafficIncreased,
    #[serde(rename = "traffic_decreased")]
    TrafficDecreased,
    #[serde(rename = "promoted")]
    Promoted,
    #[serde(rename = "rolled_back")]
    RolledBack,
    #[serde(rename = "superseded")]
    Superseded,
}

impl std::fmt::Display for RolloutEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RolloutQueued => write!(f, "rollout_queued"),
            Self::RolloutReady => write!(f, "rollout_ready"),
            Self::CanaryDeployed => write!(f, "canary_deployed"),
            Self::TrafficIncreased => write!(f, "traffic_increased"),
            Self::TrafficDecreased => write!(f, "traffic_decreased"),
            Self::Promoted => write!(f, "promoted"),
            Self::RolledBack => write!(f, "rolled_back"),
            Self::Superseded => write!(f, "superseded"),
        }
    }
}

impl Default for RolloutEventType {
    fn default() -> RolloutEventType {
        Self::RolloutQueued
    }
}
