/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RolloutState {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(
        rename = "data",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub data: Option<Option<Box<models::RolloutStateData>>>,
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "state_type")]
    pub state_type: models::RolloutStateType,
    #[serde(rename = "status")]
    pub status: models::RolloutStateStatus,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl RolloutState {
    pub fn new(
        created_at: String,
        id: u64,
        state_type: models::RolloutStateType,
        status: models::RolloutStateStatus,
        updated_at: String,
    ) -> RolloutState {
        RolloutState {
            created_at,
            data: None,
            id,
            state_type,
            status,
            updated_at,
        }
    }
}
