/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rollout {
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "application_id")]
    pub application_id: u32,
    #[serde(rename = "config")]
    pub config: Box<models::ApplicationConfig>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "events")]
    pub events: Vec<models::RolloutEvent>,
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "number")]
    pub number: u64,
    #[serde(rename = "status")]
    pub status: models::RolloutStatus,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Rollout {
    pub fn new(active: bool, application_id: u32, config: models::ApplicationConfig, created_at: String, events: Vec<models::RolloutEvent>, id: u64, number: u64, status: models::RolloutStatus, updated_at: String) -> Rollout {
        Rollout {
            active,
            application_id,
            config: Box::new(config),
            created_at,
            events,
            id,
            number,
            status,
            updated_at,
        }
    }
}

