/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RolloutStateType {
    #[serde(rename = "promote_canary")]
    PromoteCanary,
    #[serde(rename = "deploy_canary")]
    DeployCanary,
    #[serde(rename = "set_canary_traffic")]
    SetCanaryTraffic,
    #[serde(rename = "rollback_canary")]
    RollbackCanary,
    #[serde(rename = "cancel_canary")]
    CancelCanary,

}

impl std::fmt::Display for RolloutStateType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PromoteCanary => write!(f, "promote_canary"),
            Self::DeployCanary => write!(f, "deploy_canary"),
            Self::SetCanaryTraffic => write!(f, "set_canary_traffic"),
            Self::RollbackCanary => write!(f, "rollback_canary"),
            Self::CancelCanary => write!(f, "cancel_canary"),
        }
    }
}

impl Default for RolloutStateType {
    fn default() -> RolloutStateType {
        Self::PromoteCanary
    }
}

