/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrafficIncreasedData {
    #[serde(rename = "new_percent")]
    pub new_percent: u32,
}

impl TrafficIncreasedData {
    pub fn new(new_percent: u32) -> TrafficIncreasedData {
        TrafficIncreasedData {
            new_percent,
        }
    }
}

