/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDeploymentStateSuccess {
    #[serde(rename = "state")]
    pub state: Box<models::DeploymentState>,
}

impl UpdateDeploymentStateSuccess {
    pub fn new(state: models::DeploymentState) -> UpdateDeploymentStateSuccess {
        UpdateDeploymentStateSuccess {
            state: Box::new(state),
        }
    }
}
