/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRolloutStatusRequest {
    #[serde(rename = "status")]
    pub status: models::RolloutStatus,
}

impl UpdateRolloutStatusRequest {
    pub fn new(status: models::RolloutStatus) -> UpdateRolloutStatusRequest {
        UpdateRolloutStatusRequest {
            status,
        }
    }
}

