/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebServiceConfig {
    #[serde(rename = "ingress")]
    pub ingress: Box<models::IngressConfig>,
    #[serde(rename = "monitor")]
    pub monitor: Box<models::MonitorConfig>,
    #[serde(rename = "platform")]
    pub platform: Box<models::PlatformConfig>,
}

impl WebServiceConfig {
    pub fn new(
        ingress: models::IngressConfig,
        monitor: models::MonitorConfig,
        platform: models::PlatformConfig,
    ) -> WebServiceConfig {
        WebServiceConfig {
            ingress: Box::new(ingress),
            monitor: Box::new(monitor),
            platform: Box::new(platform),
        }
    }
}
