/*
 * MultiTool
 *
 * MultiTool backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceReadSuccess {
    #[serde(rename = "workspace")]
    pub workspace: Box<models::WorkspaceDetails>,
}

impl WorkspaceReadSuccess {
    pub fn new(workspace: models::WorkspaceDetails) -> WorkspaceReadSuccess {
        WorkspaceReadSuccess {
            workspace: Box::new(workspace),
        }
    }
}
